service: insultbot

custom:
  region: ${self:provider.region}
  stage: ${env:STAGE, self:custom.localConfig.stage, opt:stage, 'dev'}
  prefixAuto: ${self:service}-${self:custom.stage}
  prefix: ${env:PREFIX, self:custom.prefixAuto}
  resourceNames:
    delivery: ${self:custom.prefix}-delivery
    sqs: ${self:custom.prefix}-messages

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:ChangeMessageVisibility
      - sqs:ChangeMessageVisibilityBatch
      - sqs:DeleteMessage
      - sqs:DeleteMessageBatch
      - sqs:GetQueueAttributes
      - sqs:GetQueueUrl
      - sqs:ReceiveMessage
      - sqs:SendMessage
      - sqs:SendMessageBatch
    Resource: arn:aws:sqs:*:*:${self:custom.resourceNames.sqs}

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

resources:
  Resources:
    DeliveryMessages:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.resourceNames.sqs}
        MessageRetentionPeriod: 1209600
        VisibilityTimeout: 60

functions:
  index:
    handler: functions/index.get
    name: ${self:custom.prefix}-index
    events:
      - http: GET /
  inboxGet:
    handler: functions/inbox.get
    name: ${self:custom.prefix}-inboxGet
    events:
      - http: GET inbox
  inboxPost:
    handler: functions/inbox.post
    name: ${self:custom.prefix}-inboxPost
    events:
      - http: POST /inbox
  outboxGet:
    handler: functions/outbox.get
    name: ${self:custom.prefix}-outboxGet
    events:
      - http: GET /outbox
  periodic:
    timeout: 60
    handler: functions/periodic.handler
    name: ${self:custom.prefix}-periodic
    events:
      - schedule: rate(1 minute)
  delivery:
    timeout: 60
    handler: functions/delivery.handler
    name: ${self:custom.resourceNames.delivery}
    reservedConcurrency: 5
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - DeliveryMessages
              - Arn
